begin;

create schema if not exists dom_nutricion_catalogos;
create schema if not exists dom_nutricion_ingredientes;
create schema if not exists dom_nutricion_ingrediente_rel;
create schema if not exists dom_nutricion_reglas;

create table if not exists dom_nutricion_catalogos.grupo_alimentario (
    id integer generated by default as identity primary key,
    nombre varchar(255) not null,
    descripcion text,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create unique index if not exists ux_grupo_alimentario_nombre_dom_split
    on dom_nutricion_catalogos.grupo_alimentario (lower(btrim(nombre)));

create table if not exists dom_nutricion_catalogos.etiqueta_nutricional (
    id integer generated by default as identity primary key,
    codigo_interno varchar(100),
    nombre_categoria varchar(255) not null,
    descripcion text,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create unique index if not exists ux_etiqueta_nutricional_codigo_dom_split
    on dom_nutricion_catalogos.etiqueta_nutricional (lower(codigo_interno))
    where codigo_interno is not null;

create unique index if not exists ux_etiqueta_nutricional_nombre_dom_split
    on dom_nutricion_catalogos.etiqueta_nutricional (lower(nombre_categoria));

do $$
begin
    if not exists (
        select 1
        from information_schema.tables
        where table_schema = 'dom_nutricion_ingredientes'
          and table_name = 'ingrediente'
    ) then
        if exists (
            select 1
            from information_schema.tables
            where table_schema = 'dom_nutricion'
              and table_name = 'ingrediente'
        ) then
            execute 'create table dom_nutricion_ingredientes.ingrediente (like dom_nutricion.ingrediente including all)';
        else
            execute '
                create table dom_nutricion_ingredientes.ingrediente (
                    id integer generated by default as identity primary key,
                    nombre varchar(255) not null,
                    activo boolean not null default true,
                    created_at timestamp not null default now()
                )
            ';
        end if;
    end if;
end
$$;

create table if not exists dom_nutricion_ingrediente_rel.ingrediente_etiqueta (
    id bigserial primary key,
    id_ingrediente integer not null,
    id_etiqueta integer not null,
    valor_etiqueta varchar(255),
    created_at timestamp not null default now()
);

create unique index if not exists ux_ingrediente_etiqueta_dom_split
    on dom_nutricion_ingrediente_rel.ingrediente_etiqueta (id_ingrediente, id_etiqueta);

create table if not exists dom_nutricion_ingrediente_rel.ingrediente_nutriente (
    id bigserial primary key,
    id_ingrediente integer not null,
    id_nutriente integer,
    valor_nutriente numeric(18,6),
    created_at timestamp not null default now()
);

create index if not exists idx_ingrediente_nutriente_ingrediente_dom_split
    on dom_nutricion_ingrediente_rel.ingrediente_nutriente (id_ingrediente);

create index if not exists idx_ingrediente_nutriente_nutriente_dom_split
    on dom_nutricion_ingrediente_rel.ingrediente_nutriente (id_nutriente);

do $$
begin
    if not exists (
        select 1 from pg_constraint
        where conname = 'fk_ing_etq_ing_dom_split'
    ) then
        alter table dom_nutricion_ingrediente_rel.ingrediente_etiqueta
            add constraint fk_ing_etq_ing_dom_split
            foreign key (id_ingrediente)
            references dom_nutricion_ingredientes.ingrediente(id)
            on delete cascade;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'fk_ing_etq_etq_dom_split'
    ) then
        alter table dom_nutricion_ingrediente_rel.ingrediente_etiqueta
            add constraint fk_ing_etq_etq_dom_split
            foreign key (id_etiqueta)
            references dom_nutricion_catalogos.etiqueta_nutricional(id)
            on delete cascade;
    end if;

    if not exists (
        select 1 from pg_constraint
        where conname = 'fk_ing_nutr_ing_dom_split'
    ) then
        alter table dom_nutricion_ingrediente_rel.ingrediente_nutriente
            add constraint fk_ing_nutr_ing_dom_split
            foreign key (id_ingrediente)
            references dom_nutricion_ingredientes.ingrediente(id)
            on delete cascade;
    end if;
end
$$;

insert into dom_nutricion_catalogos.grupo_alimentario (id, nombre)
select g.id, g.nombre
from dom_nutricion.grupo_alimentario g
on conflict (id) do nothing;

insert into dom_nutricion_catalogos.etiqueta_nutricional (id, codigo_interno, nombre_categoria, descripcion, created_at)
select e.id, e.codigo_interno, e.nombre_categoria, e.descripcion, coalesce(e.created_at, now())
from dom_nutricion.etiqueta_nutricional e
on conflict (id) do nothing;

do $$
declare
    shared_cols text;
begin
    if exists (
        select 1 from information_schema.tables
        where table_schema = 'dom_nutricion'
          and table_name = 'ingrediente'
    ) then
        select string_agg(format('%I', c.column_name), ', ' order by c.ordinal_position)
        into shared_cols
        from information_schema.columns c
        inner join information_schema.columns s
            on s.column_name = c.column_name
           and s.table_schema = 'dom_nutricion'
           and s.table_name = 'ingrediente'
        where c.table_schema = 'dom_nutricion_ingredientes'
          and c.table_name = 'ingrediente';

        if shared_cols is not null then
            execute format(
                'insert into dom_nutricion_ingredientes.ingrediente (%1$s) select %1$s from dom_nutricion.ingrediente on conflict (id) do nothing',
                shared_cols
            );
        end if;
    end if;
end
$$;

insert into dom_nutricion_ingrediente_rel.ingrediente_etiqueta (
    id,
    id_ingrediente,
    id_etiqueta,
    valor_etiqueta,
    created_at
)
select
    ie.id,
    ie.ingrediente_id,
    ie.etiqueta_id,
    ie.valor_etiqueta,
    coalesce(ie.created_at, now())
from dom_nutricion.ingrediente_etiqueta ie
on conflict (id) do nothing;

select setval(
    pg_get_serial_sequence('dom_nutricion_catalogos.grupo_alimentario', 'id'),
    coalesce((select max(id) from dom_nutricion_catalogos.grupo_alimentario), 1),
    true
);

select setval(
    pg_get_serial_sequence('dom_nutricion_catalogos.etiqueta_nutricional', 'id'),
    coalesce((select max(id) from dom_nutricion_catalogos.etiqueta_nutricional), 1),
    true
);

select setval(
    pg_get_serial_sequence('dom_nutricion_ingredientes.ingrediente', 'id'),
    coalesce((select max(id) from dom_nutricion_ingredientes.ingrediente), 1),
    true
);

select setval(
    pg_get_serial_sequence('dom_nutricion_ingrediente_rel.ingrediente_etiqueta', 'id'),
    coalesce((select max(id) from dom_nutricion_ingrediente_rel.ingrediente_etiqueta), 1),
    true
);

commit;
