alter role authenticator in database postgres
set pgrst.db_schemas = 'public,storage,graphql_public,dom_auditoria_seguridad,dom_clinica_alergias,dom_clinica_controles,dom_clinica_diagnosticos,dom_clinica_objetivos,dom_compras,dom_experiencia_usuario,dom_identidad_catalogos,dom_identidad_usuarios,dom_nutricion_catalogos,dom_nutricion_ingrediente_rel,dom_nutricion_ingredientes,dom_planes_base,dom_planes_catalogos_estado,dom_planes_catalogos_tipo,dom_planes_permitidos,dom_planes_reemplazos,dom_recetas_analitica,dom_recetas_base,dom_recetas_composicion,dom_referencia_oms,dom_reglas_catalogos,dom_reglas_motor,dom_territorio_catalogos,dom_tutor_acompanamiento';

alter role authenticator
set pgrst.db_schemas = 'public,storage,graphql_public,dom_auditoria_seguridad,dom_clinica_alergias,dom_clinica_controles,dom_clinica_diagnosticos,dom_clinica_objetivos,dom_compras,dom_experiencia_usuario,dom_identidad_catalogos,dom_identidad_usuarios,dom_nutricion_catalogos,dom_nutricion_ingrediente_rel,dom_nutricion_ingredientes,dom_planes_base,dom_planes_catalogos_estado,dom_planes_catalogos_tipo,dom_planes_permitidos,dom_planes_reemplazos,dom_recetas_analitica,dom_recetas_base,dom_recetas_composicion,dom_referencia_oms,dom_reglas_catalogos,dom_reglas_motor,dom_territorio_catalogos,dom_tutor_acompanamiento';

notify pgrst, 'reload config';
notify pgrst, 'reload schema';
