name: reuma_nutri_app
description: Base multimodal para soporte nutricional clinico pediatrico
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.8.0
  dio: 5.8.0+1
  http: ^1.2.2
  intl: ^0.20.0
  google_fonts: ^6.2.1
  fl_chart: ^1.2.0
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  image: ^4.2.0
  flutter_image_compress: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo 1.webp
    - assets/images/logo sin.webp
    - assets/images/catalogo_condiciones.webp
    - assets/images/gestion.webp
    - assets/images/gestion_pacientes.webp
    - assets/images/kp3.webp
    - assets/images/kpi_1.webp
    - assets/images/kpi_3.webp
    - assets/images/kpi_joint.webp
    - assets/images/kpi_total.webp
    - assets/images/modal_icon_mi.webp
    - assets/images/nutri_clinic_hero.webp
    - assets/images/pacientes.webp
    - assets/images/rule_joint_icon.webp
    - assets/images/rule_temporal_icon.webp

