name: reuma_nutri_app
description: Base multimodal para soporte nutricional clinico pediatrico
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.8.0
  dio: 5.8.0+1
  http: ^1.2.2
  intl: ^0.20.0
  google_fonts: ^6.2.1
  fl_chart: ^1.2.0
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  image: ^4.2.0
  flutter_image_compress: ^2.4.0
  pdf: ^3.12.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_reuma_nutri.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_adaptive_foreground.png"
  web:
    generate: true
    image_path: "assets/images/logo_reuma_nutri.png"
    background_color: "#ffffff"
    theme_color: "#026eb5"
  windows:
    generate: true
    image_path: "assets/images/logo_reuma_nutri.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/images/LOGO.png
    - assets/images/logo 1.webp
    - assets/images/logo sin.webp
    - assets/images/catalogo_condiciones.webp
    - assets/images/gestion.webp
    - assets/images/gestion_pacientes.webp
    - assets/images/kp3.webp
    - assets/images/kpi_1.webp
    - assets/images/kpi_3.webp
    - assets/images/kpi_joint.webp
    - assets/images/kpi_total.webp
    - assets/images/modal_icon_mi.webp
    - assets/images/pacientes.webp
    - assets/images/rule_joint_icon.webp
    - assets/images/rule_temporal_icon.webp
    - assets/images/clinica.png
    - assets/images/temporal.png
    - assets/images/logoReumaNutri.svg
    - assets/images/logo_final.svg
    - assets/images/logo_reuma_nutri.png

